### ISSUE TITLE
How to pick use case clarification

### ISSUE THREAD

**Issue by kylemcmearty** [jacopotagliabue/reclist#15]
### Description

When I pick a use case from Reclist and I want to build off of one of them, eg complementary items, does that mean I would instantiate the `CoveoCartRecList` class?

From the Colab notebook tutorial:

`In particular in this tutorial, we are targeting a "complementary items" use cases, such as for example a cart recommender:

if a shopper added item X to the cart, what is she likely to add next? We train a simple, yet effective prod2vec baseline [model](https://arxiv.org/abs/2007.14906), re-using for convenience a "training embedding" function already implemented by recsys.
`

For example, say I'm interested in the similar item or session based use cases from RecList, would I call `MovieLensSimilarItemRecList` or `SpotifySessionRecList()` to start my build from?

I'm trying to get some clarification on the right way to use this library from the blog post and colab notebook when it says "Step #1 Pick a use case"

Thank you

**Comment by jacopotagliabue** [comment]
Hi! Sorry for the delay, it's been a terrible week!

Thanks for writing to us! I'm happy to jump on a call and discuss use cases together so we can guide you better and get your feedback: generally speaking:

Coveo example = complementary example
MovieLens = similarity example
Spotify = sequential example

If you ping me through email, happy to do a walkthrough - email is my last name DOT my first name AT gmail.com !

Thanks again!
