### ISSUE TITLE
Reclist tutorial - Hit Rate by Brand graph

### ISSUE THREAD

**Issue by kylemcmearty** [jacopotagliabue/reclist#16]
### Description

I ran through the provided RecList Colab Notebook tutorial. I also read the blog on RecList.

In the blog post, it shows the Hit Rate @ 10 by brand. Picture below.

![image](https://user-images.githubusercontent.com/10493854/205373947-3b88c287-5992-465b-a0f1-e74848175f9a.png)

I did not see how to generate the HR@10 by brand in the Colab Notebook example. Would you mind sharing the code on how to generate that please?

Thank you

**Comment by jacopotagliabue** [comment]
Hi @kmcmearty thanks for writing!

That pic (also in the paper originally) was generate with the original private dataset (https://arxiv.org/abs/2111.09963), sorry about the confusion.

As mentioned in the other comment, please do reach out and I'm happy to spend some time discussing your use case together!

Thanks again for the question!
